using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
//add by myself
using DevExpress.XtraGrid.Views.Base;
using DevExpress.XtraGrid.Views.BandedGrid;
//add by myself

using System.Data.Entity;

namespace WindowsFormsApp1
{

    

    //what is this???????????????????????????????????
    public partial class frm_Save : DevExpress.XtraEditors.XtraForm
    {
        CharityEntities4 db = new CharityEntities4();
        public frm_Save()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            WindowsFormsApp1.CharityEntities4 dbContext = new WindowsFormsApp1.CharityEntities4();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.View_Person.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    gridControl1.DataSource = dbContext.View_Person.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void Frm_Save_Load(object sender, EventArgs e)
        {
           this.tbl_Recived_ServicesTableAdapter.Fill(this.charityDataSet1.tbl_Recived_Services);

            dateTimeSelector_BirthDate.UsePersianFormat = true;
            dateTimeSelector_CoveringBeginningDate.UsePersianFormat = true;
            dateTimeSelector_EndOfCoveringDate.UsePersianFormat = true;
            dateTimeSelector_RenewedCoveringDate.UsePersianFormat = true;
            dateTimeSelector_RenewedStatusChangeDate.UsePersianFormat = true;
            dateTimeSelector_StatusChangeDate.UsePersianFormat = true;


            //fn_FillPerson();
        }

        void fn_FillPerson()
        {

            WindowsFormsApp1.CharityEntities4 dbContext = new WindowsFormsApp1.CharityEntities4();
            dbContext.View_Person.LoadAsync().ContinueWith(loadTask =>
            {//.OrderByDescending(x=>x.id)
                gridControl1.DataSource = dbContext.View_Person.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
            //this.view_PersonTableAdapter.Fill(this.charityDataSet.View_Person);
        }

  void fn_SearchPerson(string input_txt)
        {

            WindowsFormsApp1.CharityEntities4 dbContext = new WindowsFormsApp1.CharityEntities4();
            dbContext.View_Person.LoadAsync().ContinueWith(loadTask =>
            {//.OrderByDescending(x=>x.id)
                gridControl1.DataSource = dbContext.View_Person.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
            //this.view_PersonTableAdapter.Fill(this.charityDataSet.View_Person);
        }

        private void BtnSave_Click(object sender, EventArgs e)
        {
            
        }

        private void Btn_Delete_Click(object sender, EventArgs e)
        {
            WindowsFormsApp1.CharityEntities4 dbContext = new WindowsFormsApp1.CharityEntities4();
            dbContext.tbl_RelativeName.LoadAsync().ContinueWith(loadTask =>
            {
                gridControl1.DataSource = dbContext.tbl_RelativeName.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
            //this.view_PersonTableAdapter.Fill(this.charityDataSet.View_Person);

        }

        private void CheckButton1_CheckedChanged(object sender, EventArgs e)
        {

        }

        private void DateTimeSelector2_Click(object sender, EventArgs e)
        {

        }

        private void Txt_FileNo_KeyPress(object sender, KeyPressEventArgs e)
        {
            MyClasses.FnAcceptDigit(e);
        }

        private void Btn_Save_Click(object sender, EventArgs e)
        {

            if (
                txt_FamilyNo.Text.Length > 0 //&&
                                             //txt_AbsentNo.Text.Length > 0  
                )
            {
                tbl_Persons MyPerson = new tbl_Persons()
                {
                    Name = txt_Name.Text,
                    Address = rtx_Address.Text,
                    FamilyNo = int.Parse(txt_FamilyNo.Text),


                   // AbsentNo = int.Parse(txt_AbsentNo.Text),
                    FileNumber = int.Parse(txt_FileNumber.Text),
                    BirthDate = dateTimeSelector_BirthDate.Value,
                    CoveringBeginningDate = dateTimeSelector_CoveringBeginningDate.Value,
                    RenewedStatusChangeDate = dateTimeSelector_RenewedStatusChangeDate.Value,
                    StatusChangeDate = dateTimeSelector_StatusChangeDate.Value,
                    EndOfCoveringDate = dateTimeSelector_EndOfCoveringDate.Value,


                    CauseOfNotCovering = txt_CauseOfNotCovering.Text,
                    ClothSize = txt_ClothSize.Text,
                    Description = rtx_Descriptions.Text,

                    FamilyName = txt_FamilyName.Text,
                    FatherName = txt_FatherName.Text,
                    Grade = txt_Grade.Text,

                    NationalCode = txt_NationalCode.Text,
                    PhoneNo = txt_PhoneNo.Text,
                    ShoeSize = txt_ShoeSize.Text,
                    CaretakerInfo = rtx_CaretakerInfo.Text,
                    

                    Sex = toggleSwitch1.IsOn,
                    //Recived_Services_ID = (int)cmb_ServiceStatus.SelectedValue

                };



                // ///////////////////////////////////////////
                // WindowsFormsApp1.CharityEntities4 dbContext = new WindowsFormsApp1.CharityEntities4();

                //string id = txt_Name.Text;
                // if (dbContext.View_Person.FirstOrDefault(x => x.Name == id) != null)
                // {
                //     MessageBox.Show("این رکورد وجود دارد", "", MessageBoxButtons.OK, MessageBoxIcon.Warning);

                // }
                // /////////////////////////////////////////// 

                db.tbl_Persons.Add(MyPerson);
                db.SaveChanges();
                fn_FillPerson();
            }
            else
            {
                MessageBox.Show("مقادیر کامل نیست", "خطا", MessageBoxButtons.OK, MessageBoxIcon.Warning);
            }
        }

        private void Btn_Clear_CheckedChanged(object sender, EventArgs e)
        {
            MyClasses.FnClearForm_No_GridControl(this.Controls);
        }

        private void Txt_NationalCode_KeyPress(object sender, KeyPressEventArgs e)
        {
            MyClasses.FnAcceptDigit(e);
        }

        private void Txt_FamilyNo_KeyPress(object sender, KeyPressEventArgs e)
        {
            MyClasses.FnAcceptDigit(e);
        }

        private void Txt_PhoneNo_KeyPress(object sender, KeyPressEventArgs e)
        {
            MyClasses.FnAcceptDigit(e);
        }

        private void Btn_Update_CheckedChanged(object sender, EventArgs e)
        {
            fn_FillPerson();
        }

        private void SearchControl1_SelectedValueChanged(object sender, EventArgs e)
        {
            DataBaseClass.FnfillSearchPersonal(ref gridControl1, searchControl1.Text);
        }

        private void SearchControl1_TextChanged(object sender, EventArgs e)
        {
 DataBaseClass.FnfillSearchPersonal(ref gridControl1, searchControl1.Text);
        }

        private void GridControl1_Click(object sender, EventArgs e)
        {
        



            //txt_PersonalNo.Text = v.PersonalNo;
            //txt_Name.Text = v.Name;
            //txt_Family.Text = v.family;
            //txt_FatherNmae.Text = v.FatherName;
            //txt_ShenasnameNo.Text = v.ShenasnameNo;
            //txt_NationalCode.Text = v.NationalCode;
            //txt_BirthLocation.Text = v.BirthLocation;
            //dateTimeSelector_Birthday.Value = v.BrithDate;
            //ts_Gender.IsOn = v.gender.ToSafeBool();
            //Ts_maritialStatus.IsOn = v.isMarried.ToSafeBool();
            //nud_childCount.Value = v.ChildNo.ToSafeInt();
            //Cb_PersonalStatus.SelectedValue = v.PersonalStatusId;
            //Cb_Position.SelectedValue = v.PositionStatusId;
            //txt_MobileNo.Text = v.MobileNo;
            //txt_PhoneNo.Text = v.PhoneNo;
            //txt_EMSPhoneNo.Text = v.EmergencyPhone;
            //Cb_licence.SelectedValue = v.LicenceId;
            //txt_BankAccount.Text = v.BankAccount;
            //txt_InsuranceNo.Text = v.InsuranceNo;
            //dateTimeSelector_FiredDate.Value = v.FireDate;
            //dateTimeSelector_HireDate.Value = v.HireDate;

            //txt_Address.Text = v.Address;
            //txt_Explaination.Text = v.Description;


            //Bitmap MyBmp = null;
            //if (v.PersonalImageAddress == null || v.PersonalImageAddress.Length < 5)
            //    MyBmp = Properties.Resources.DefaultPersonalImage;
            //else
            //    MyBmp = new Bitmap(v.PersonalImageAddress);


            //pictureBox1.Image = MyBmp;
            //lbl_Id.Caption = v.id.ToString();
        }
        //
        //
        //
        private void ویرایشToolStripMenuItem_Click(object sender, EventArgs e)
        {
            var v = (View_Person)gridView1.GetFocusedRow();


            var vv = DataBaseClass.FnFindPersonal(v.id);
            if (vv != null)
            {
                txt_Name.Text = vv.Name;
                txt_FamilyName.Text = vv.FamilyName;
                txt_FatherName.Text = vv.FatherName;
                txt_FileNumber.Text = vv.FileNumber.ToString();
                txt_CauseOfNotCovering.Text = vv.CauseOfNotCovering;
                txt_ClothSize.Text = vv.ClothSize;
                txt_FileNumber.Text = vv.FileNumber.ToString();
                txt_Grade.Text = vv.FileNumber.ToString();
                txt_NationalCode.Text = vv.NationalCode;
                txt_PhoneNo.Text = vv.PhoneNo;
                txt_ShoeSize.Text = vv.ShoeSize;
                rtx_CaretakerInfo.Text = vv.CaretakerInfo;
                //dateTimeSelector_BirthDate.DateTimeFormat = vv.BirthDate.ToSafeDateTime


                

                /////////////////////////////////////////////////////////////////////////////////////////

            }
        }

        private void حذفToolStripMenuItem_Click(object sender, EventArgs e)
        {
            var v = (View_Person)gridView1.GetFocusedRow();

             DataBaseClass.FnDeletePersonal(v.id);
            fn_FillPerson();
        }

        private void Btn_Save_CheckedChanged(object sender, EventArgs e)
        {

        }
    }
}